### ISSUE TITLE
Developing in standard web applications without Visual Studio

### ISSUE THREAD

**Issue by AdamMiltonBarker** [Microsoft/Cognitive-Speech-STT-JavaScript#10]
Hi I came across this and it is perfect for what I need but I want to add it to an existing web system that is not built in Visual Studio, how would I add this service to an existing HTML/JS/PHP website or do you have to use Visual Studio.

**Comment by tftoledo** [comment]
Use the index.htm file and JavaScript speech.1.0.0.js that will work in your application.

**Comment by jasonvomsft** [comment]
@AdamMiltonBarker, @tftoledo is correct.  The sample doesn't have any dependency to the sample other than for debugging purposes.

I will go ahead and close this out for now.  Thanks.

**Comment by AdamMiltonBarker** [comment]
Sorry for delayed reply. After a long and painful process of battling with the web speech API and reducing the quality of our systems, I am going to implement this now and see how it plays out, from testing through the demo it is more accurate than the web speech api, will follow up with an article with relevant tags. Thanks for the response guys.

**Comment by AdamMiltonBarker** [comment]
Ah I see calls per second are still an issue, I came across this with LUIS which is why I moved to another provider for our initial prototype, something you guys should look into, if you are wanting businesses to build successful products out of your services, you need to be a lot more flexible on usage, will have to find another provider, this will not fulfil our requirements, shame is it was quite accurate.

**Comment by AdamMiltonBarker** [comment]
Sorry but does not appear that the provided code  is what I tried out on the demo, the script is calling a file, I am look to do continuous recognition in a browser as in the demo provided on MS cognitive services. Would rather ask a direct question than spend days searching through docs to find out it is not possible, thanks.

**Comment by AdamMiltonBarker** [comment]
Over 10 second response time, anyway to avoid this?

**Comment by AdamMiltonBarker** [comment]
Will submit pull request if desired, cannot solve the 10 -15 second delay though...

https://github.com/AdamMiltonBarker/Cognitive-Speech-STT-JavaScript/tree/master/BubbleWrap
