### ISSUE TITLE
The LUIS version was 2.0 and an error occurred during execution.

### ISSUE THREAD

**Issue by T-Umezaki** [Microsoft/Cognitive-Speech-STT-JavaScript#15]
The LUIS version was 2.0 and an error occurred during execution.
I will post the modified code here.
Speech1.0.0.js: 817

        LuisClient.kServiceUrl = "https://api.projectoxford.ai/luis/v2.0/apps/";
        LuisClient.prototype.getIntent = function (text) {
            var task = new Task();
            var request = new XMLHttpRequest();
            request.open('GET', [
                LuisClient.kServiceUrl,
                this._prefs.luisAppId, 
                "?subscription-key=",
                this._prefs.luisSubscriptionId, 
                "&q=", 
                text

**Comment by priyaravi20** [comment]
Please add this to LUIS user forum.
