### ISSUE TITLE
Voice commands instance limits

### ISSUE THREAD

**Issue by xxGizmoCodexx** [Microsoft/Cognitive-Speech-STT-JavaScript#16]
Using the JS library, only allows a user to issue 6 voice commands per page load. This seems to be due to the following error: 

> Uncaught DOMException: Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).

The error occurs in speech.1.0.0.js at Line 379:
` _this.context = new AudioContext();`

I suspect this is due to the  AudioContext never being closed when the library is done processing the voice sentence and thus after 6 occurrences, the limit is hit and no further voice clips can be recorded.

Hope this issue breakdown helps.
Feedback on this issue would be appreciated

**Comment by priyaravi20** [comment]
Please retest. I was able to continue sending multiple commands with no restrictions.
