### ISSUE TITLE
Apostrophe not recognized

### ISSUE THREAD

**Issue by schirag1993** [Microsoft/Cognitive-Speech-STT-JavaScript#18]
Hi, working on Bing Speech API for simple speech to text conversions. However, I noticed apostrophes are not being recognized or added. Is there any way this small issue can be avoided or fixed? Or does it need to be programmatically corrected?

For example, if the spoken statement is "Send me Mary's number", the converted text becomes:
"send me marys number". 

Need the converted text to be:
"send me mary's number"

**Comment by priyaravi20** [comment]
We do not support apostrophes currently.
