### ISSUE TITLE
[Speech.JS] Partial results never show up.

### ISSUE THREAD

**Issue by margaretmz** [Microsoft/Cognitive-Speech-STT-JavaScript#2]
_From @doplumi on April 4, 2016 10:17_

The `onPartialResults` callback present in `index.htm` does never fire. 
Is this a bug or just not a feature yet?

_Copied from original issue: Microsoft/ProjectOxford-ClientSDK#42_

**Comment by jasonvomsft** [comment]
@doplumi, onPartialResults is not implemented currently as was intended to keep parity with the native SDKs.
