### ISSUE TITLE
Do we have a WebSocket API reference for continuous Speech Recognition?

### ISSUE THREAD

**Issue by margaretmz** [Microsoft/Cognitive-Speech-STT-JavaScript#4]
_From @parijat1209 on April 25, 2016 7:33_

Hi,

Speech.JS cannot do continuous recognition as the Partial Response is never received. I believe SpeechClient dll is connecting to Bing WebSocket servers for the continuous recognition to happen. Can't we directly connect to Bing WebSocket servers from HTML5 WebSockets? If so, then where can I find a sample code or a reference to directly connect to the Bing Speech WebSocket servers using JavaScript WebSockets?

Thanks

_Copied from original issue: Microsoft/ProjectOxford-ClientSDK#58_

**Comment by margaretmz** [comment]
_From @dmiller235623 on May 3, 2016 0:50_

connect to my outlook email not my gmail.. I get a lot of
spam...dmiller235623@outlook.com

**Comment by margaretmz** [comment]
_From @ochakov on May 30, 2016 21:6_

+1

**Comment by margaretmz** [comment]
_From @sushma-ananda on June 13, 2016 18:58_

We are looking at disable Barge-in on ASR (c#.net) module of Project Oxford Speech API. Can you please help suggest us onm this?

**Comment by williamsandstrom** [comment]
I'm also looking for this. I've looked at the request from the client SDK for Windows using Fiddler and there is web socket endpoints available there

This are what the sent headers from the library looks like

https://websockets.platform.bing.com/ws/speech/recognize

```
GET /ws/speech/recognize HTTP/1.1
Connection: Upgrade
Upgrade: Websocket
Authorization: Bearer ashdjashdjlasd
User-Agent: Mozilla/4.0 (Windows 8; Unknown;Unknown;ProcessName/AppName=Unknown;DeviceType=Near;SpeechClient=1.0.716436)
X-WebSocketConnectionId: 4eb71213ef974307826d4c89639ddf53
X-CU-LogLevel: 1
X-Search-AppID: Unknown
X-Search-Market: en-US
X-Search-UILang: en-US
Sec-WebSocket-Key: lS4KX2vWHDnmiO3UnECc8A==
Sec-WebSocket-Version: 13
Host: websockets.platform.bing.com
```

This makes things bad since I cannot add custom headers to a websocket in JS.

If you are able to add the authorization header to your websocket request, then you can use the code above. Also see their [demo](https://www.microsoft.com/cognitive-services/en-us/speech-api) which uses partial response/streaming, but it uses it's own endpoint (https://cog-web-wu.azurewebsites.net/cognitive-services/ws/speechtotextdemo?language=en-US&g_Recaptcha_Response=null&isNeedVerify=false). If we could somehow add the authorization header to a web socket, we could replace the demo endpoint with the real endpoint and have a full working partial response support in JS.

**Comment by javenosa** [comment]
+1 on this, I want to implement continous recognition, where can I find a sample or documentation about this?
Thanks.

**Comment by beeva-ivanmarques** [comment]
+1

**Comment by tbass134** [comment]
+1

**Comment by jasonvomsft** [comment]
We currently only support continuous reco using the published SDKs.

**Comment by pimente** [comment]
Do you plan to support continuous reco with the [Bing Speech-to-Text Javascript SDK
](https://github.com/Microsoft/Cognitive-Speech-STT-JavaScript) at some point ?
If so, do you have an approximate estimate time ?
If not, are you willing to share the specifications with the community for us to implement it ?
Thank you

**Comment by pavanagrawal123** [comment]
Hi!

Has there been an update on the issue? Has the SDK started to support the continuous recognition through websockets? I see that the demo page does support the continuous recognition... what are they using to do that?

**Comment by PrabuLK** [comment]
Hi,

 In web application using client library unable to get continuous recognition, Is there any way we can get continuous recognition. We are implementing this on .Net MVC application.

**Comment by AdamMiltonBarker** [comment]
I have noticed the same, I guess it is not supported, such a shame that the service does not actually represent what the demo shows.

**Comment by AdamMiltonBarker** [comment]
My response to this guys, as I had the same frustrations. I doubt it is worth me issuing a pull request as doubt it will get accepted but here is a way to semi automate recognition, as long as you reply within 5 seconds, will spend more time on it in the future but feel free to use it as a base to get where you need to go:

https://github.com/AdamMiltonBarker/Cognitive-Speech-STT-JavaScript/tree/master/BubbleWrap

**Comment by TheRusskiy** [comment]
@AdamMiltonBarker the link is dead. Have you removed it?

**Comment by priyaravi20** [comment]
We currently do not have a websocket based implementation in JavaScript. Please look for the next release for this addition.

**Comment by javenosa** [comment]
@priyaravi20 What is the next release date?

**Comment by rajbir123** [comment]
@priyaravi20 /microsoft guys...  how the speech will be dynamic/runtime based on user stop speaking
# I mean the user can speak continuously and their should be timeout when the user stop speaking(any particular time like 5 or 6 seconds the user stop speaking and then it throw out the final output like we have in siri apple)
