### ISSUE TITLE
NPM Package for Speech.js

### ISSUE THREAD

**Issue by margaretmz** [Microsoft/Cognitive-Speech-STT-JavaScript#7]
_From @theluk on April 30, 2016 13:1_

create a package.json and submit a package to the npm registry.

Required steps
1. The Speech.js should not access global variables like `window` or `navigator` #61 
2. The Speech.js should be wrapped in UMD factory pattern
3. The Speech.js should not call `SpeechMain()` automatically on load #61 
4. A package.json should be created and published to npm-registry

_Copied from original issue: Microsoft/ProjectOxford-ClientSDK#62_

**Comment by akanieski** [comment]
This would be a really nice thing to have available in at least one modern package manager (npm, bower)

**Comment by priyaravi20** [comment]
Thanks for the comment. We will be publishing this in the next version.
