### ISSUE TITLE
Only shortPhrase can be selected, and changing audio file does not change results..

### ISSUE THREAD

**Issue by sleeplessTLV** [Microsoft/Cognitive-Speech-STT-JavaScript#8]
Hi, I've downloaded the latest, and running it fine. In the microphone mode I get results commensurate with what I say.
When I do NOT choose microphone (I'm actually looking to use this for files in batch), I get the 'weather' related reply EVEN WHEN I change the Contents of the demo file whatstheweatherlike.wav... which is weird.
Furthermore, I cannot choose 'longDictation' - it does not appear in the pull down menu, the only option appearing is 'shortPhrase'

**Comment by beeva-manuelfranco** [comment]
Hi,
Any news about when is going to be available the "SpeechRecognitionMode.longDictation" mode in the Speech.js library?
Thanks,

**Comment by jasonvomsft** [comment]
Hi @beeva-manuelfranco and @sleeplessTLV Long form dictation will not be a supported feature of the REST API which the JS API uses due to long running POSTs.

**Comment by beeva-manuelfranco** [comment]
Thank you @jasonvomsft.
Currently I am using "Long Dictation" mode with the Windows .NET SDK, but I need to do the same with a javascript client (customer requirement)?
So, is it possible to use Bing Speech "Long Dictation" mode from a javascript client somehow?

**Comment by priyaravi20** [comment]
We will be enabling this feature when we release a websocket implementation for JavaScript in the coming releases.
