### ISSUE TITLE
Transcription output with Bing Speech API

### ISSUE THREAD

**Issue by tftoledo** [Microsoft/Cognitive-Speech-STT-JavaScript#9]
I am using the Bing Speech API (with Javascript - REST API) and as a result get something like this:

`[{ 
  "lexical":"gerson de laudos médicos por meio do reconhecimento automático",
  "display":"gerson de laudos por meio do reconhecimento automático",
  "inverseNormalization":null,
  "maskedInverseNormalization":null,
  "transcript":"gerson de laudos por meio do reconhecimento automático",
  "confidence":0.7618318
}]`

How do I get the result is just what is transcribed? For example, I would like to output only was the text: "gerson de laudos médicos por meio do reconhecimento automático".

**Comment by priyaravi20** [comment]
Currently you will need to explicitly look for "transcript" in the JSON. We are looking to simplify this in the future.
